version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: raquet-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: emer
      MONGO_INITDB_ROOT_PASSWORD: 261019
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: raquet-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSER: emer
      ME_CONFIG_MONGODB_ADMINPASSWORD: 261019
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongodb-data: